# Datos del Titanic

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
titanic = sns.load_dataset("titanic")

In [3]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
titanic.shape

(891, 15)

In [5]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
titanic["survived"] = pd.Categorical(titanic["survived"])

In [7]:
titanic["pclass"] = pd.Categorical(titanic["pclass"])

In [8]:
titanic["sex"] = pd.Categorical(titanic["sex"])

## Tablas de contingencia de una variable

In [9]:
tab = pd.crosstab(index=titanic["survived"],
                 columns="pasajeros")
tab

col_0     pasajeros
survived
0               549
1               342

In [10]:
type(tab)

pandas.core.frame.DataFrame

In [11]:
pd.crosstab(index=titanic["pclass"],
           columns="pasajeros")

col_0   pasajeros
pclass
1             216
2             184
3             491

In [12]:
pd.crosstab(index=titanic["sex"],
           columns="pasajeros")

col_0   pasajeros
sex
female        314
male          577

In [13]:
pd.crosstab(index=titanic["deck"],
           columns="pasajeros")

col_0  pasajeros
deck
A             15
B             47
C             59
D             33
E             32
F             13
G              4

In [14]:
tab_c = pd.crosstab(index=titanic["deck"],
                    columns="pasajeros")
tab_c

col_0  pasajeros
deck
A             15
B             47
C             59
D             33
E             32
F             13
G              4

In [15]:
tab_c.sum()

col_0
pasajeros    203
dtype: int64

In [16]:
tab_c.shape

(7, 1)

In [17]:
tab_c.iloc[1:5]

col_0  pasajeros
deck
B             47
C             59
D             33
E             32

In [18]:
tab_c/tab_c.sum() # Tabla de frecuencias relativas

col_0  pasajeros
deck
A       0.073892
B       0.231527
C       0.290640
D       0.162562
E       0.157635
F       0.064039
G       0.019704

## Tablas de contingencia de dos variables

In [19]:
survived_sex = pd.crosstab(index=titanic["survived"],
                          columns=titanic["sex"])
survived_sex.index = ["died", "survived"]
survived_sex

sex       female  male
died          81   468
survived     233   109

In [20]:
survived_class = pd.crosstab(index=titanic["survived"], 
                            columns=titanic["pclass"],
                            margins=True)

survived_class.index = ["murio", "sobrevivio", "total_clase"]
survived_class.columns = ["primera", "segunda", "tercera", "total_superv"]
survived_class

             primera  segunda  tercera  total_superv
murio             80       97      372           549
sobrevivio       136       87      119           342
total_clase      216      184      491           891

### Frecuencias relativas globales

In [21]:
survived_class/survived_class.loc["total_clase", "total_superv"] # porcentajes en base al total de supervivientes

              primera   segunda   tercera  total_superv
murio        0.089787  0.108866  0.417508      0.616162
sobrevivio   0.152637  0.097643  0.133558      0.383838
total_clase  0.242424  0.206510  0.551066      1.000000

### Frecuencias relativas marginales

In [22]:
survived_class/survived_class.loc["total_clase"] # porcentaje en base a los supervivientes de cada una de las clases

             primera   segunda   tercera  total_superv
murio        0.37037  0.527174  0.757637      0.616162
sobrevivio   0.62963  0.472826  0.242363      0.383838
total_clase  1.00000  1.000000  1.000000      1.000000

In [23]:
survived_class.div(survived_class.loc["total_clase"], axis=1) # otra forma porcentaje en base a los supervivientes de cada una de las clases

             primera   segunda   tercera  total_superv
murio        0.37037  0.527174  0.757637      0.616162
sobrevivio   0.62963  0.472826  0.242363      0.383838
total_clase  1.00000  1.000000  1.000000      1.000000

In [24]:
survived_class.T/survived_class["total_superv"] # frecuencias relativas marginales por filas

                 murio  sobrevivio  total_clase
primera       0.145719    0.397661     0.242424
segunda       0.176685    0.254386     0.206510
tercera       0.677596    0.347953     0.551066
total_superv  1.000000    1.000000     1.000000

In [25]:
survived_class.div(survived_class["total_superv"], axis=0) # otra forma frecuencias relativas marginales por filas

              primera   segunda   tercera  total_superv
murio        0.145719  0.176685  0.677596           1.0
sobrevivio   0.397661  0.254386  0.347953           1.0
total_clase  0.242424  0.206510  0.551066           1.0

## Tablas multi dimensionales

In [26]:
surv_sex_class  = pd.crosstab(index=titanic["survived"],
                             columns=[titanic["sex"], titanic["pclass"]],
                             margins=True)
surv_sex_class

sex      female          male            All
pclass        1   2    3    1    2    3
survived
0             3   6   72   77   91  300  549
1            91  70   72   45   17   47  342
All          94  76  144  122  108  347  891

In [27]:
surv_sex_class["female"] # subclase de las mujeres

pclass     1   2    3
survived
0          3   6   72
1         91  70   72
All       94  76  144

In [28]:
surv_sex_class["female"][1] # subclase de las mujeres de la primera clase

survived
0       3
1      91
All    94
Name: 1, dtype: int64

In [29]:
surv_sex_class/surv_sex_class.loc["All"] # frecuencias relativas

sex         female                     male                           All
pclass           1         2    3         1         2         3
survived
0         0.031915  0.078947  0.5  0.631148  0.842593  0.864553  0.616162
1         0.968085  0.921053  0.5  0.368852  0.157407  0.135447  0.383838
All       1.000000  1.000000  1.0  1.000000  1.000000  1.000000  1.000000